/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqlGUI;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Napo Escritorio
 */
public class frmSintaxis extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmSintaxis() {
        
        initComponents();
        jPimagen.setVisible(true);
        jPTabla.setVisible(false);
        jPRegistro.setVisible(false);
        jPSelectJoin.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("SqlUC Sintaxis");
        setIconImage(new ImageIcon(getClass().getResource("/ImagesGUI/SqlUC.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/ImagesGUI/FondoSQLUC.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPTabla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaCurso = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaCurso2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPRegistro = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPSelectJoin = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPimagen = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTablas = new javax.swing.JMenu();
        menuRegistros = new javax.swing.JMenu();
        menuSelectJoin = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        jPTabla.setBackground(new java.awt.Color(255, 255, 255));
        jPTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)), "SINTAXIS EN TABLAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT", 0, 11), new java.awt.Color(204, 102, 0))); // NOI18N
        jPTabla.setForeground(new java.awt.Color(204, 102, 0));
        jPTabla.setPreferredSize(new java.awt.Dimension(570, 460));

        jLabel1.setText("CREAR");

        jLabel2.setText("MODIFICAR");

        jLabel3.setText("ELIMINAR");

        jLabel4.setText("CREAR TABLA nombre_tabla CAMPOS campo1, … , campoN CLAVE campo1    LONGITUD #");

        jLabel5.setText("La longitud sera el tamaño máximo que tendrán los registros.");

        ListaCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ListaCurso);
        if (ListaCurso.getColumnModel().getColumnCount() > 0) {
            ListaCurso.getColumnModel().getColumn(0).setResizable(false);
            ListaCurso.getColumnModel().getColumn(1).setResizable(false);
            ListaCurso.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel6.setText("CREAR TABLA ListaCurso CAMPOS Cedula,Nombre,Apellido CLAVE Cedula    LONGITUD 12");

        jLabel7.setText("MODIFICAR TABLA nombre_tabla CAMPO nombre_campo POR nombre_campo");

        jLabel8.setText("MODIFICAR TABLA ListaCurso CAMPO Apellido POR Apellidos");

        jLabel9.setText("ELIMINAR TABLA nombre_tabla");

        jLabel10.setText("ELIMINAR TABLA ListaCurso");

        ListaCurso2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ListaCurso2);
        if (ListaCurso2.getColumnModel().getColumnCount() > 0) {
            ListaCurso2.getColumnModel().getColumn(0).setResizable(false);
            ListaCurso2.getColumnModel().getColumn(1).setResizable(false);
            ListaCurso2.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel11.setText("Se borra lógicamente es decir se mantiene en el Archivo META");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Solo se puede hacer si no hay registros.");

        javax.swing.GroupLayout jPTablaLayout = new javax.swing.GroupLayout(jPTabla);
        jPTabla.setLayout(jPTablaLayout);
        jPTablaLayout.setHorizontalGroup(
            jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTablaLayout.createSequentialGroup()
                        .addGroup(jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addGroup(jPTablaLayout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(jLabel2))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addContainerGap(99, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTablaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTablaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap())))
        );
        jPTablaLayout.setVerticalGroup(
            jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTablaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jPRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)), "SINTAXIS EN REGISTROS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT Black", 1, 12), new java.awt.Color(204, 102, 0))); // NOI18N
        jPRegistro.setForeground(new java.awt.Color(204, 102, 0));
        jPRegistro.setPreferredSize(new java.awt.Dimension(560, 460));

        jLabel13.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 102, 0));
        jLabel13.setText("CREAR");

        jLabel14.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 102, 0));
        jLabel14.setText("MODIFICAR");

        jLabel15.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 102, 0));
        jLabel15.setText("ELIMINAR");

        jLabel16.setText("CREAR REGISTRO nombre_tabla VALOR vCampo1 , vCampo2 ,... , vCampoN ");

        jLabel18.setText("CREAR REGISTRO ListaCurso VALOR 0106418534,Benito,Farfan ");

        jLabel19.setText("MODIFICAR REGISTRO nombre_tabla CLAVE valorCampoClave CAMPO campo POR valor_campo_nuevo ");

        jLabel20.setText("MODIFICAR REGISTRO ListaCurso CLAVE 0106418534 CAMPO Benito  POR Mauricio ");

        jLabel21.setText("ELIMINAR REGISTRO nombre_tabla CLAVE valorCampoClave ");

        jLabel22.setText("ELIMINAR REGISTRO ListaCurso CLAVE 0106418534 ");

        javax.swing.GroupLayout jPRegistroLayout = new javax.swing.GroupLayout(jPRegistro);
        jPRegistro.setLayout(jPRegistroLayout);
        jPRegistroLayout.setHorizontalGroup(
            jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroLayout.createSequentialGroup()
                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRegistroLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel13))
                    .addGroup(jPRegistroLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(jLabel14))
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)))
                    .addGroup(jPRegistroLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel15))
                    .addComponent(jLabel19)
                    .addGroup(jPRegistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPRegistroLayout.setVerticalGroup(
            jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(76, 76, 76)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(89, 89, 89)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPSelectJoin.setBackground(new java.awt.Color(255, 255, 255));
        jPSelectJoin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)), "SINTAXIS ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT Black", 1, 12), new java.awt.Color(204, 102, 0))); // NOI18N
        jPSelectJoin.setForeground(new java.awt.Color(204, 102, 0));
        jPSelectJoin.setPreferredSize(new java.awt.Dimension(560, 460));

        jLabel17.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 102, 0));
        jLabel17.setText("SELECT");

        jLabel23.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 102, 0));
        jLabel23.setText("JOIN");

        jLabel25.setText("SELECCIONAR DE nombre_tabla DONDE nombre_campo = “Algo”");

        jLabel26.setText("SELECCIONAR DE ListaCurso  DONDE Nombre = “Patricio”");

        jLabel27.setText("UNIR nombre_tabla1, nombre_tabla2 POR nombre_campo=”Algo\"");

        jLabel28.setText("UNIR ListaCurso, ListaFacultar POR nombre=”Patricio\"");

        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("Muestra los registros que tengan ese valor en ese campo.");

        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("Une dos tablas por el campo indicado");

        javax.swing.GroupLayout jPSelectJoinLayout = new javax.swing.GroupLayout(jPSelectJoin);
        jPSelectJoin.setLayout(jPSelectJoinLayout);
        jPSelectJoinLayout.setHorizontalGroup(
            jPSelectJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSelectJoinLayout.createSequentialGroup()
                .addGroup(jPSelectJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPSelectJoinLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel17))
                    .addGroup(jPSelectJoinLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPSelectJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)))
                    .addGroup(jPSelectJoinLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel23)))
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSelectJoinLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPSelectJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSelectJoinLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSelectJoinLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(45, 45, 45))))
        );
        jPSelectJoinLayout.setVerticalGroup(
            jPSelectJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSelectJoinLayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(51, 51, 51)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(47, 47, 47)
                .addComponent(jLabel30)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPimagen.setOpaque(false);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesGUI/IconCodeMakers.fw.png"))); // NOI18N

        javax.swing.GroupLayout jPimagenLayout = new javax.swing.GroupLayout(jPimagen);
        jPimagen.setLayout(jPimagenLayout);
        jPimagenLayout.setHorizontalGroup(
            jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPimagenLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPimagenLayout.setVerticalGroup(
            jPimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPimagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuTablas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesGUI/listado.fw.png"))); // NOI18N
        menuTablas.setText("Tablas");
        menuTablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTablasMouseClicked(evt);
            }
        });
        menuTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablasActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuTablas);

        menuRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesGUI/buscarlistadolapiz.fw.png"))); // NOI18N
        menuRegistros.setText("Registros");
        menuRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegistrosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRegistros);

        menuSelectJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesGUI/buscar.fw.png"))); // NOI18N
        menuSelectJoin.setText("Select & Join");
        menuSelectJoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSelectJoinMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSelectJoin);

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesGUI/equis.fw.png"))); // NOI18N
        menuSalir.setText("Regresar");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPimagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                            .addComponent(jPSelectJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPSelectJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasActionPerformed
      
    }//GEN-LAST:event_menuTablasActionPerformed

    private void menuTablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTablasMouseClicked
        jPTabla.setVisible(true);
        jPRegistro.setVisible(false);
        jPSelectJoin.setVisible(false);
        jPimagen.setVisible(false);

    }//GEN-LAST:event_menuTablasMouseClicked

    private void menuRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistrosMouseClicked
        // TODO add your handling code here:
        jPTabla.setVisible(false); 
        jPRegistro.setVisible(true);
        jPSelectJoin.setVisible(false);
        jPimagen.setVisible(false);
    }//GEN-LAST:event_menuRegistrosMouseClicked

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
 
          new frmSql().setVisible(true); 
          this.setVisible(true); 
          dispose();
    }//GEN-LAST:event_menuSalirMouseClicked

    private void menuSelectJoinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSelectJoinMouseClicked
        jPTabla.setVisible(false); 
        jPRegistro.setVisible(false);
        jPSelectJoin.setVisible(true);
        jPimagen.setVisible(false);
    }//GEN-LAST:event_menuSelectJoinMouseClicked

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSintaxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSintaxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSintaxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSintaxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSintaxis().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListaCurso;
    private javax.swing.JTable ListaCurso2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPRegistro;
    private javax.swing.JPanel jPSelectJoin;
    private javax.swing.JPanel jPTabla;
    private javax.swing.JPanel jPimagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuSelectJoin;
    private javax.swing.JMenu menuTablas;
    // End of variables declaration//GEN-END:variables
}
